### ISSUE TITLE
命令行导入图像识别

### ISSUE THREAD

**Issue by yizhao266** [sangyuxiaowu/Snipping_OCR#2]
可以增加命令行导入图像识别吗？对我来说这很有用，谢谢！

**Comment by sangyuxiaowu** [comment]
可以具体说说你想如何实现嘛？是其他系统调用？

**Comment by sangyuxiaowu** [comment]
这个工具更多的是UI的操作，你可以使用工具的ocr引擎 PaddleOCR
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/doc/doc_ch/quickstart.md

**Comment by yizhao266** [comment]
> 可以具体说说你想如何实现嘛？是其他系统调用？
我希望能够快速获取图像文本，目前Snipping_OCR对中英文的识别速度和质量是最好的之一。交互方式再快速点将是完美的。我希望程序能够采纳以下两点优化建议。
1.能够处理命令行导入的图像（拖拽到程序快捷方式图标上就可以自动OCR工作），像ABBYY FineReader OCR那样的。这将可以用来被所有支持发送到其他程序的截图软件调用。
2.增加一个能够启动程序就执行截图OCR的选项，这类似[Text-Grab](https://github.com/TheJoeFin/Text-Grab)的Open Fullscreen on Launch选项。
上面两项特性Text-Grab都具有，但是对中英文文字识别PaddleOCR引擎要优于Tesseract-OCR和Windows OCR。所以非常期待你对Snipping_OCR的开发增强，
最后，感谢你的工作，愿你的每一天都充满阳光和欢笑！

**Comment by sangyuxiaowu** [comment]
https://github.com/sangyuxiaowu/Snipping_OCR/releases/tag/v1.3.5
